// scripts/seed.ts
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { products } from "../lib/db/schema";

const db = drizzle(new Database(process.env.DATABASE_URL ?? "./dev.db"));
const now = new Date();

const seed = [
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro 128 Go",
    slug: "iphone-16-pro",
    category_id: "smartphones",
    subcategory_id: "iphone",
    price: 899000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Le smartphone le plus avancé d'Apple avec la puce A18 Pro et le système de caméra Pro Camera.",
    specs: JSON.stringify({ Processeur: "Apple A18 Pro", Stockage: "128 Go", RAM: "8 Go", Écran: "6,3 po Super Retina XDR", Batterie: "3 274 mAh", OS: "iOS 18" }),
    stock: 10, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "samsung-galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    category_id: "smartphones",
    subcategory_id: "samsung-galaxy",
    price: 799000, old_price: null, brand: "Samsung",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "L'ultra-flagship de Samsung avec S Pen intégré et IA Galaxy avancée.",
    specs: JSON.stringify({ Processeur: "Snapdragon 8 Elite", Stockage: "256 Go", RAM: "12 Go", Écran: "6,9 po QHD+ AMOLED", Batterie: "5 000 mAh" }),
    stock: 7, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "iphone-15",
    name: "iPhone 15 128 Go",
    slug: "iphone-15",
    category_id: "smartphones",
    subcategory_id: "iphone",
    price: 649000, old_price: 749000, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "iPhone 15 avec Dynamic Island, puce A16 Bionic et port USB-C.",
    specs: JSON.stringify({ Processeur: "Apple A16 Bionic", Stockage: "128 Go", Écran: "6,1 po Super Retina XDR", Batterie: "3 349 mAh" }),
    stock: 15, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "google-pixel-9-pro",
    name: "Google Pixel 9 Pro",
    slug: "google-pixel-9-pro",
    category_id: "smartphones",
    subcategory_id: "google-pixel",
    price: 650000, old_price: null, brand: "Google",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Le smartphone Google avec IA Gemini intégrée et les meilleures photos de nuit.",
    specs: JSON.stringify({ Processeur: "Google Tensor G4", Stockage: "128 Go", RAM: "12 Go", Écran: "6,3 po LTPO OLED", Batterie: "4 700 mAh" }),
    stock: 6, badge: null, is_active: true, created_at: now,
  },
  {
    id: "xiaomi-14t-pro",
    name: "Xiaomi 14T Pro",
    slug: "xiaomi-14t-pro",
    category_id: "smartphones",
    subcategory_id: "xiaomi",
    price: 375000, old_price: 450000, brand: "Xiaomi",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Flagship killer Xiaomi avec Leica Camera System et charge 120W.",
    specs: JSON.stringify({ Processeur: "Dimensity 9300+", Stockage: "256 Go", RAM: "12 Go", Écran: "6,67 po AMOLED 144 Hz", Batterie: "5 000 mAh" }),
    stock: 12, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "macbook-air-m4",
    name: "MacBook Air M4 15 po",
    slug: "macbook-air-m4",
    category_id: "ordinateurs",
    subcategory_id: "laptops",
    price: 1150000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Le MacBook Air le plus fin et le plus rapide jamais conçu, avec la puce M4.",
    specs: JSON.stringify({ Processeur: "Apple M4", RAM: "16 Go", Stockage: "512 Go SSD", Écran: "15,3 po Liquid Retina", Autonomie: "18h" }),
    stock: 5, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "lenovo-ideapad-slim-5",
    name: "Lenovo IdeaPad Slim 5",
    slug: "lenovo-ideapad-slim-5",
    category_id: "ordinateurs",
    subcategory_id: "laptops",
    price: 449000, old_price: 520000, brand: "Lenovo",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Ultrabook fin et léger pour la productivité quotidienne avec écran OLED.",
    specs: JSON.stringify({ Processeur: "Intel Core Ultra 7", RAM: "16 Go", Stockage: "512 Go SSD", Écran: "14 po OLED" }),
    stock: 4, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "ipad-pro-m4",
    name: "iPad Pro M4 11 po",
    slug: "ipad-pro-m4",
    category_id: "tablettes",
    subcategory_id: "ipad",
    price: 950000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "L'iPad le plus puissant avec la puce M4 et l'écran Ultra Retina XDR.",
    specs: JSON.stringify({ Processeur: "Apple M4", Stockage: "256 Go", Écran: "11 po Ultra Retina XDR", Connectivité: "Wi-Fi 6E" }),
    stock: 8, badge: null, is_active: true, created_at: now,
  },
  {
    id: "ipad-mini-7",
    name: "iPad mini 7",
    slug: "ipad-mini-7",
    category_id: "tablettes",
    subcategory_id: "ipad",
    price: 549000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "L'iPad compact et puissant avec puce A17 Pro et Apple Pencil Pro.",
    specs: JSON.stringify({ Processeur: "Apple A17 Pro", Stockage: "128 Go", Écran: "8,3 po Liquid Retina" }),
    stock: 7, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "samsung-galaxy-tab-s10",
    name: "Samsung Galaxy Tab S10",
    slug: "samsung-galaxy-tab-s10",
    category_id: "tablettes",
    subcategory_id: "samsung-tab",
    price: 475000, old_price: 520000, brand: "Samsung",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Tablette Android premium avec S Pen inclus et écran Dynamic AMOLED 2X.",
    specs: JSON.stringify({ Processeur: "Snapdragon 8 Gen 3", Stockage: "256 Go", RAM: "12 Go", Écran: "11 po Dynamic AMOLED 2X", Batterie: "8 000 mAh" }),
    stock: 9, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "airpods-pro-3",
    name: "AirPods Pro 3",
    slug: "airpods-pro-3",
    category_id: "audio",
    subcategory_id: "ecouteurs-sans-fil",
    price: 189000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Réduction de bruit active de nouvelle génération avec son Spatial Audio.",
    specs: JSON.stringify({ Autonomie: "6h + 30h boîtier", Connexion: "Bluetooth 5.3", Résistance: "IP54" }),
    stock: 15, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "airpods-4",
    name: "AirPods 4",
    slug: "airpods-4",
    category_id: "audio",
    subcategory_id: "ecouteurs-sans-fil",
    price: 139000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Les AirPods de nouvelle génération avec réduction de bruit active.",
    specs: JSON.stringify({ Autonomie: "5h + 30h boîtier", Connexion: "Bluetooth 5.3" }),
    stock: 20, badge: null, is_active: true, created_at: now,
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    category_id: "audio",
    subcategory_id: "casques",
    price: 225000, old_price: 280000, brand: "Sony",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Le meilleur casque à réduction de bruit du marché avec 30h d'autonomie.",
    specs: JSON.stringify({ Autonomie: "30h", Connexion: "Bluetooth 5.2", Réduction: "8 microphones HD" }),
    stock: 8, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "jbl-charge-5",
    name: "JBL Charge 5",
    slug: "jbl-charge-5",
    category_id: "audio",
    subcategory_id: "enceintes-bluetooth",
    price: 89000, old_price: null, brand: "JBL",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Enceinte portable puissante avec batterie 7 500 mAh et résistance IP67.",
    specs: JSON.stringify({ Autonomie: "20h", Résistance: "IP67", Puissance: "30W" }),
    stock: 18, badge: null, is_active: true, created_at: now,
  },
  {
    id: "apple-watch-ultra-3",
    name: "Apple Watch Ultra 3",
    slug: "apple-watch-ultra-3",
    category_id: "montres",
    subcategory_id: "apple-watch",
    price: 599000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "La montre connectée la plus robuste d'Apple, conçue pour les aventuriers.",
    specs: JSON.stringify({ Écran: "49 mm Always-On Retina", Autonomie: "60h", Résistance: "100m" }),
    stock: 3, badge: null, is_active: true, created_at: now,
  },
  {
    id: "samsung-galaxy-watch-7",
    name: "Samsung Galaxy Watch 7",
    slug: "samsung-galaxy-watch-7",
    category_id: "montres",
    subcategory_id: "samsung-galaxy-watch",
    price: 199000, old_price: 250000, brand: "Samsung",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Montre connectée Samsung avec suivi santé avancé et Wear OS.",
    specs: JSON.stringify({ Écran: "40 mm Super AMOLED", Autonomie: "40h", Résistance: "5ATM" }),
    stock: 11, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "google-pixel-watch-3",
    name: "Google Pixel Watch 3",
    slug: "google-pixel-watch-3",
    category_id: "montres",
    subcategory_id: "google-pixel-watch",
    price: 299000, old_price: null, brand: "Google",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Montre connectée Google avec Wear OS et suivi santé Fitbit intégré.",
    specs: JSON.stringify({ Écran: "45 mm AMOLED", Autonomie: "24h", Résistance: "5ATM" }),
    stock: 5, badge: null, is_active: true, created_at: now,
  },
  {
    id: "anker-usb-c-hub",
    name: "Anker USB-C Hub 7-en-1",
    slug: "anker-usb-c-hub",
    category_id: "accessoires",
    subcategory_id: "supports-docks",
    price: 25000, old_price: null, brand: "Anker",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Hub USB-C 7 ports : HDMI 4K, 3x USB 3.0, lecteur SD, USB-C 100W PD.",
    specs: JSON.stringify({ Ports: "7", HDMI: "4K@30Hz", USB: "3x USB 3.0", Alimentation: "100W PD" }),
    stock: 25, badge: null, is_active: true, created_at: now,
  },
  {
    id: "apple-magsafe-charger",
    name: "Apple MagSafe Chargeur 15W",
    slug: "apple-magsafe-charger",
    category_id: "accessoires",
    subcategory_id: "chargeurs-cables",
    price: 29000, old_price: null, brand: "Apple",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Chargeur MagSafe officiel Apple 15W pour iPhone 12 et ultérieurs.",
    specs: JSON.stringify({ Puissance: "15W", Compatibilité: "iPhone 12+", Longueur: "1m" }),
    stock: 30, badge: null, is_active: true, created_at: now,
  },
  {
    id: "samsung-galaxy-buds-3-pro",
    name: "Samsung Galaxy Buds 3 Pro",
    slug: "samsung-galaxy-buds-3-pro",
    category_id: "audio",
    subcategory_id: "ecouteurs-sans-fil",
    price: 129000, old_price: null, brand: "Samsung",
    images: JSON.stringify(["/images/products/placeholder.svg"]),
    description: "Écouteurs Samsung avec réduction de bruit et son haute résolution Hi-Fi.",
    specs: JSON.stringify({ Autonomie: "6h + 24h boîtier", Connexion: "Bluetooth 5.4" }),
    stock: 14, badge: null, is_active: true, created_at: now,
  },
];

async function main() {
  console.log("Seeding products...");
  await db.delete(products);
  await db.insert(products).values(seed);
  console.log(`✓ ${seed.length} produits insérés`);
}

main().catch((err) => {
  console.error("[seed] Erreur fatale:", err);
  process.exit(1);
});
