// scripts/seed.ts
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { products } from "../lib/db/schema";

const db = drizzle(new Database(process.env.DATABASE_URL ?? "./dev.db"));
const now = new Date();
const img = ["/images/products/placeholder.svg"];

const seed = [
  // ── SMARTPHONES ─────────────────────────────────────────────────────────────

  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    slug: "iphone-17-pro-max",
    category_id: "smartphones", subcategory_id: "iphone",
    price: 1299000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "iPhone 17 Pro Max — le summum de la gamme Apple avec la puce A19 Pro, système de caméra Pro ultra-perfectionné et écran ProMotion 6,9 po.",
    specs: JSON.stringify({ Processeur: "Apple A19 Pro", Stockage: "256 Go", RAM: "12 Go", Écran: "6,9 po ProMotion OLED", OS: "iOS 18" }),
    stock: 8, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "iphone-17-air",
    name: "iPhone 17 Air",
    slug: "iphone-17-air",
    category_id: "smartphones", subcategory_id: "iphone",
    price: 899000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "iPhone 17 Air — ultra-fin, ultra-léger, avec eSIM et le meilleur rapport taille/performance de la gamme.",
    specs: JSON.stringify({ Processeur: "Apple A19", Stockage: "128 Go", Écran: "6,1 po Super Retina XDR", OS: "iOS 18" }),
    stock: 10, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "huawei-mate-xt",
    name: "Huawei Mate XT Ultimate",
    slug: "huawei-mate-xt",
    category_id: "smartphones", subcategory_id: "huawei",
    price: 1099000, old_price: null, brand: "Huawei",
    images: JSON.stringify(img),
    description: "Le premier smartphone pliable triple-écran au monde. Design iconique, performances exceptionnelles.",
    specs: JSON.stringify({ Processeur: "Kirin 9010", Stockage: "512 Go", RAM: "16 Go", Écran: "10,2 po tri-fold OLED", Batterie: "5 600 mAh" }),
    stock: 4, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "huawei-pura-80-ultra",
    name: "Huawei Pura 80 Ultra",
    slug: "huawei-pura-80-ultra",
    category_id: "smartphones", subcategory_id: "huawei",
    price: 899000, old_price: null, brand: "Huawei",
    images: JSON.stringify(img),
    description: "Huawei Pura 80 Ultra — photographie computationnelle de pointe avec optique Leica et zoom périscopique 200×.",
    specs: JSON.stringify({ Processeur: "Kirin 9020", Stockage: "256 Go", RAM: "12 Go", Écran: "6,8 po OLED 120 Hz", Batterie: "5 500 mAh" }),
    stock: 6, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "honor-magic-v5",
    name: "HONOR Magic V5",
    slug: "honor-magic-v5",
    category_id: "smartphones", subcategory_id: "autres-marques",
    price: 799000, old_price: null, brand: "Honor",
    images: JSON.stringify(img),
    description: "HONOR Magic V5 — smartphone pliable le plus fin du marché avec IA embarquée et autonomie record.",
    specs: JSON.stringify({ Processeur: "Snapdragon 8 Elite", Stockage: "256 Go", RAM: "16 Go", Écran: "7,9 po OLED pliable", Batterie: "5 150 mAh" }),
    stock: 5, badge: null, is_active: true, created_at: now,
  },
  {
    id: "oneplus-15",
    name: "OnePlus 15",
    slug: "oneplus-15",
    category_id: "smartphones", subcategory_id: "autres-marques",
    price: 699000, old_price: null, brand: "OnePlus",
    images: JSON.stringify(img),
    description: "OnePlus 15 — flagship ultra-rapide avec charge 100W, écran LTPO 2K et système Hasselblad.",
    specs: JSON.stringify({ Processeur: "Snapdragon 8 Elite", Stockage: "256 Go", RAM: "12 Go", Écran: "6,78 po LTPO AMOLED 2K", Batterie: "6 000 mAh", Charge: "100W" }),
    stock: 7, badge: null, is_active: true, created_at: now,
  },
  {
    id: "xiaomi-15-ultra",
    name: "Xiaomi 15 Ultra",
    slug: "xiaomi-15-ultra",
    category_id: "smartphones", subcategory_id: "xiaomi",
    price: 749000, old_price: null, brand: "Xiaomi",
    images: JSON.stringify(img),
    description: "Xiaomi 15 Ultra — photographie Leica quadri-caméra et charge rapide 90W dans un design premium.",
    specs: JSON.stringify({ Processeur: "Snapdragon 8 Elite", Stockage: "512 Go", RAM: "16 Go", Écran: "6,73 po AMOLED 120 Hz", Batterie: "6 000 mAh" }),
    stock: 5, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "nothing-phone-a3-pro",
    name: "Nothing Phone A3 Pro",
    slug: "nothing-phone-a3-pro",
    category_id: "smartphones", subcategory_id: "autres-marques",
    price: 379000, old_price: null, brand: "Nothing",
    images: JSON.stringify(img),
    description: "Nothing Phone A3 Pro — interface unique avec Glyph Interface LED et design transparent iconique.",
    specs: JSON.stringify({ Processeur: "Snapdragon 7s Gen 3", Stockage: "256 Go", RAM: "8 Go", Écran: "6,77 po OLED 120 Hz", Batterie: "5 000 mAh" }),
    stock: 12, badge: null, is_active: true, created_at: now,
  },
  {
    id: "google-pixel-10-pro",
    name: "Google Pixel 10 Pro",
    slug: "google-pixel-10-pro",
    category_id: "smartphones", subcategory_id: "google-pixel",
    price: 799000, old_price: null, brand: "Google",
    images: JSON.stringify(img),
    description: "Google Pixel 10 Pro — IA Gemini Ultra intégrée, meilleures photos de nuit du marché et 7 ans de mises à jour.",
    specs: JSON.stringify({ Processeur: "Google Tensor G5", Stockage: "256 Go", RAM: "16 Go", Écran: "6,3 po LTPO OLED", Batterie: "5 000 mAh" }),
    stock: 6, badge: null, is_active: true, created_at: now,
  },

  // ── TABLETTES ────────────────────────────────────────────────────────────────

  {
    id: "galaxy-tab-s11-ultra",
    name: "Samsung Galaxy Tab S11 Ultra",
    slug: "galaxy-tab-s11-ultra",
    category_id: "tablettes", subcategory_id: "samsung-tab",
    price: 749000, old_price: null, brand: "Samsung",
    images: JSON.stringify(img),
    description: "Galaxy Tab S11 Ultra — tablette 14,6 po Dynamic AMOLED 2X avec S Pen et WiFi 7.",
    specs: JSON.stringify({ Processeur: "Snapdragon 8 Elite", Stockage: "256 Go", RAM: "12 Go", Écran: "14,6 po Dynamic AMOLED 2X", Batterie: "11 200 mAh" }),
    stock: 5, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "ipad-m5-pro",
    name: "iPad Pro M5 11 po",
    slug: "ipad-m5-pro",
    category_id: "tablettes", subcategory_id: "ipad",
    price: 1050000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "iPad Pro M5 — la tablette la plus puissante avec puce M5, écran Ultra Retina XDR OLED et Apple Intelligence.",
    specs: JSON.stringify({ Processeur: "Apple M5", Stockage: "256 Go", Écran: "11 po Ultra Retina XDR OLED", Connectivité: "Wi-Fi 7" }),
    stock: 6, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "ipad-a16-2025",
    name: "iPad Air A16 2025",
    slug: "ipad-a16-2025",
    category_id: "tablettes", subcategory_id: "ipad",
    price: 699000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "iPad Air A16 — moderne et classe, avec puce A16 Bionic et compatibilité Apple Pencil Pro.",
    specs: JSON.stringify({ Processeur: "Apple A16", Stockage: "128 Go", Écran: "11 po Liquid Retina", Connectivité: "Wi-Fi 6E" }),
    stock: 8, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "ipad-10e-generation",
    name: "iPad 10e Génération",
    slug: "ipad-10e-generation",
    category_id: "tablettes", subcategory_id: "ipad",
    price: 399000, old_price: 449000, brand: "Apple",
    images: JSON.stringify(img),
    description: "iPad 10e génération — tablette polyvalente avec puce A14 Bionic, écran 10,9 po et connecteur USB-C.",
    specs: JSON.stringify({ Processeur: "Apple A14 Bionic", Stockage: "64 Go", Écran: "10,9 po Liquid Retina" }),
    stock: 14, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "ipad-11e-generation",
    name: "iPad 11e Génération",
    slug: "ipad-11e-generation",
    category_id: "tablettes", subcategory_id: "ipad",
    price: 499000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "iPad 11e génération — puissant, coloré et fin, avec puce A16 et support Apple Intelligence.",
    specs: JSON.stringify({ Processeur: "Apple A16", Stockage: "128 Go", Écran: "10,9 po Liquid Retina", Connectivité: "Wi-Fi 6E" }),
    stock: 10, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "remarkable-paper-pro",
    name: "reMarkable Paper Pro",
    slug: "remarkable-paper-pro",
    category_id: "tablettes", subcategory_id: "tablettes-android",
    price: 449000, old_price: null, brand: "reMarkable",
    images: JSON.stringify(img),
    description: "reMarkable Paper Pro — la tablette d'écriture la plus proche du papier, avec écran Color Paper et stylet précis.",
    specs: JSON.stringify({ Écran: "11,8 po Color Paper", Stockage: "64 Go", Autonomie: "Several weeks", Stylet: "Marker Plus" }),
    stock: 4, badge: null, is_active: true, created_at: now,
  },

  // ── ORDINATEURS ──────────────────────────────────────────────────────────────

  {
    id: "macbook-air-m4",
    name: "MacBook Air M4",
    slug: "macbook-air-m4",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 999000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "MacBook Air M4 — ultra-fin, ultra-rapide, avec puce M4 et jusqu'à 18h d'autonomie.",
    specs: JSON.stringify({ Processeur: "Apple M4", RAM: "16 Go", Stockage: "256 Go SSD", Écran: "13,6 po Liquid Retina", Autonomie: "18h" }),
    stock: 7, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "macbook-pro-14-m5",
    name: "MacBook Pro 14 po M5",
    slug: "macbook-pro-14-m5",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 1699000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "MacBook Pro 14 M5 — performances professionnelles avec puce M5 et écran Liquid Retina XDR.",
    specs: JSON.stringify({ Processeur: "Apple M5", RAM: "24 Go", Stockage: "512 Go SSD", Écran: "14,2 po Liquid Retina XDR", Autonomie: "22h" }),
    stock: 4, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "macbook-pro-m4",
    name: "MacBook Pro M4",
    slug: "macbook-pro-m4",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 1499000, old_price: 1699000, brand: "Apple",
    images: JSON.stringify(img),
    description: "MacBook Pro M4 tout neuf AZERTY — clavier français, puce M4 Pro et écran Mini-LED ProMotion 120 Hz.",
    specs: JSON.stringify({ Processeur: "Apple M4 Pro", RAM: "24 Go", Stockage: "512 Go SSD", Écran: "14,2 po Liquid Retina XDR", Autonomie: "24h" }),
    stock: 3, badge: "Promo", is_active: true, created_at: now,
  },
  {
    id: "macbook-m4-pro-max",
    name: "MacBook Pro M4 Pro Max 16 po",
    slug: "macbook-m4-pro-max",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 2199000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "MacBook Pro M4 Pro Max 16 po — la puissance de travail ultime pour la création de contenu et le développement.",
    specs: JSON.stringify({ Processeur: "Apple M4 Max", RAM: "48 Go", Stockage: "1 To SSD", Écran: "16,2 po Liquid Retina XDR", Autonomie: "22h" }),
    stock: 3, badge: null, is_active: true, created_at: now,
  },
  {
    id: "imac-m4",
    name: "iMac M4",
    slug: "imac-m4",
    category_id: "ordinateurs", subcategory_id: "tout-en-un",
    price: 1599000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "iMac M4 — tout-en-un Apple avec écran Retina 4,5K 24 po et puce M4. Stock prêt.",
    specs: JSON.stringify({ Processeur: "Apple M4", RAM: "16 Go", Stockage: "256 Go SSD", Écran: "24 po Retina 4,5K", Couleurs: "7 coloris" }),
    stock: 4, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "mac-mini-m4",
    name: "Mac Mini M4",
    slug: "mac-mini-m4",
    category_id: "ordinateurs", subcategory_id: "desktops",
    price: 699000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "Mac Mini M4 — le bureau le plus compact d'Apple avec puce M4, format ultra-discret et performances élevées.",
    specs: JSON.stringify({ Processeur: "Apple M4", RAM: "16 Go", Stockage: "256 Go SSD", Ports: "3x USB-C, 2x USB-A, HDMI, Ethernet" }),
    stock: 8, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "hp-envy-x360",
    name: "HP ENVY x360",
    slug: "hp-envy-x360",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 649000, old_price: null, brand: "HP",
    images: JSON.stringify(img),
    description: "HP ENVY x360 — convertible 2-en-1 avec processeur Intel Core Ultra et écran tactile OLED 360°.",
    specs: JSON.stringify({ Processeur: "Intel Core Ultra 7", RAM: "16 Go", Stockage: "512 Go SSD", Écran: "14 po OLED tactile 360°" }),
    stock: 5, badge: null, is_active: true, created_at: now,
  },
  {
    id: "microsoft-surface-pro-11",
    name: "Microsoft Surface Pro 11",
    slug: "microsoft-surface-pro-11",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 1199000, old_price: null, brand: "Microsoft",
    images: JSON.stringify(img),
    description: "Microsoft Surface Pro 11e édition OL — tablette PC avec Copilot+ et processeur Snapdragon X Elite.",
    specs: JSON.stringify({ Processeur: "Snapdragon X Elite", RAM: "16 Go", Stockage: "256 Go SSD", Écran: "13 po PixelSense Flow OLED" }),
    stock: 4, badge: null, is_active: true, created_at: now,
  },
  {
    id: "microsoft-surface-pro-12",
    name: "Microsoft Surface Pro 12",
    slug: "microsoft-surface-pro-12",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 1299000, old_price: null, brand: "Microsoft",
    images: JSON.stringify(img),
    description: "Nouvelle Surface Pro 12 Copilot+ PC — la tablette PC la plus avancée de Microsoft avec IA intégrée.",
    specs: JSON.stringify({ Processeur: "Snapdragon X Plus", RAM: "16 Go", Stockage: "512 Go SSD", Écran: "13 po PixelSense OLED" }),
    stock: 3, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "microsoft-surface-laptop-7",
    name: "Microsoft Surface Laptop 7",
    slug: "microsoft-surface-laptop-7",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 1099000, old_price: null, brand: "Microsoft",
    images: JSON.stringify(img),
    description: "Microsoft Surface Laptop 7 — laptop Copilot+ ultra-fin avec Snapdragon X Elite et autonomie 22h.",
    specs: JSON.stringify({ Processeur: "Snapdragon X Elite", RAM: "16 Go", Stockage: "512 Go SSD", Écran: "15 po PixelSense IPS", Autonomie: "22h" }),
    stock: 4, badge: null, is_active: true, created_at: now,
  },
  {
    id: "hp-omnibook-x-flip",
    name: "HP OmniBook X Flip",
    slug: "hp-omnibook-x-flip",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 849000, old_price: null, brand: "HP",
    images: JSON.stringify(img),
    description: "HP OmniBook X Flip — ordinateur portable 2-en-1 Copilot+ avec Snapdragon X Plus et écran tactile.",
    specs: JSON.stringify({ Processeur: "Snapdragon X Plus", RAM: "16 Go", Stockage: "512 Go SSD", Écran: "14 po OLED tactile" }),
    stock: 5, badge: null, is_active: true, created_at: now,
  },
  {
    id: "lenovo-legion-t5-gaming",
    name: "Lenovo Légion T5 Gaming",
    slug: "lenovo-legion-t5-gaming",
    category_id: "ordinateurs", subcategory_id: "desktops",
    price: 649000, old_price: null, brand: "Lenovo",
    images: JSON.stringify(img),
    description: "Lenovo Légion T5 Gaming — tour gaming puissante avec carte graphique dédiée et refroidissement avancé.",
    specs: JSON.stringify({ Processeur: "Intel Core i7-14700F", RAM: "16 Go DDR5", Stockage: "512 Go SSD + 1 To HDD", GPU: "NVIDIA RTX 4060" }),
    stock: 3, badge: null, is_active: true, created_at: now,
  },
  {
    id: "lenovo-legion-7-pro-oled",
    name: "Lenovo Légion 7 Pro OLED 2025",
    slug: "lenovo-legion-7-pro-oled",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 1299000, old_price: null, brand: "Lenovo",
    images: JSON.stringify(img),
    description: "Lenovo Légion 7 Pro OLED 2025 — laptop gaming avec écran OLED 165 Hz, RTX 4080 et refroidissement Legion Coldfront.",
    specs: JSON.stringify({ Processeur: "AMD Ryzen 9 8945HX", RAM: "32 Go DDR5", Stockage: "1 To SSD", GPU: "NVIDIA RTX 4080", Écran: "16 po OLED 165 Hz" }),
    stock: 3, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "asus-rog-strix-g17",
    name: "ASUS ROG Strix G17",
    slug: "asus-rog-strix-g17",
    category_id: "ordinateurs", subcategory_id: "laptops",
    price: 1199000, old_price: null, brand: "ASUS",
    images: JSON.stringify(img),
    description: "ASUS ROG Strix G17 — ordinateur portable gaming haute performance avec écran 300 Hz et RGB ROG.",
    specs: JSON.stringify({ Processeur: "AMD Ryzen 9 7945HX", RAM: "16 Go DDR5", Stockage: "1 To SSD", GPU: "NVIDIA RTX 4070", Écran: "17,3 po FHD 300 Hz" }),
    stock: 4, badge: null, is_active: true, created_at: now,
  },

  // ── MONTRES CONNECTÉES ───────────────────────────────────────────────────────

  {
    id: "galaxy-watch-7-ultra",
    name: "Samsung Galaxy Watch 7 Ultra",
    slug: "galaxy-watch-7-ultra",
    category_id: "montres", subcategory_id: "samsung-galaxy-watch",
    price: 349000, old_price: null, brand: "Samsung",
    images: JSON.stringify(img),
    description: "Galaxy Watch 7 Ultra — montre connectée premium en titane avec suivi santé avancé et autonomie record.",
    specs: JSON.stringify({ Boîtier: "47 mm titane", Écran: "Super AMOLED", Autonomie: "60h", Résistance: "10ATM", OS: "Wear OS 5" }),
    stock: 8, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "huawei-watch-ultimate-2",
    name: "Huawei Watch Ultimate 2",
    slug: "huawei-watch-ultimate-2",
    category_id: "montres", subcategory_id: "huawei-watch",
    price: 399000, old_price: null, brand: "Huawei",
    images: JSON.stringify(img),
    description: "Huawei Watch Ultimate 2 — montre connectée haut de gamme en saphir et titane avec plongée jusqu'à 100m.",
    specs: JSON.stringify({ Boîtier: "48 mm titane", Écran: "LTPO AMOLED", Autonomie: "14 jours", Résistance: "100m" }),
    stock: 5, badge: null, is_active: true, created_at: now,
  },
  {
    id: "huawei-watch-gt5-pro",
    name: "Huawei Watch GT5 Pro",
    slug: "huawei-watch-gt5-pro",
    category_id: "montres", subcategory_id: "huawei-watch",
    price: 199000, old_price: null, brand: "Huawei",
    images: JSON.stringify(img),
    description: "Huawei Watch GT5 Pro — montre connectée élégante avec suivi santé complet et autonomie 14 jours.",
    specs: JSON.stringify({ Boîtier: "46 mm titane", Écran: "AMOLED 1,43 po", Autonomie: "14 jours", Résistance: "5ATM" }),
    stock: 10, badge: null, is_active: true, created_at: now,
  },
  {
    id: "huawei-watch-5",
    name: "Huawei Watch 5",
    slug: "huawei-watch-5",
    category_id: "montres", subcategory_id: "huawei-watch",
    price: 179000, old_price: null, brand: "Huawei",
    images: JSON.stringify(img),
    description: "Huawei Watch 5 — l'excellence en matière de suivi santé avec ECG, température cutanée et GPS intégré.",
    specs: JSON.stringify({ Boîtier: "46 mm alu", Écran: "AMOLED", Autonomie: "7 jours", GPS: "Multi-constellation" }),
    stock: 12, badge: null, is_active: true, created_at: now,
  },
  {
    id: "whoop-5-life",
    name: "WHOOP 5.0 LIFE",
    slug: "whoop-5-life",
    category_id: "montres", subcategory_id: "autres-montres",
    price: 199000, old_price: null, brand: "WHOOP",
    images: JSON.stringify(img),
    description: "WHOOP 5.0 LIFE — tracker de santé et performance porté au poignet, sans écran, suivi 24h/24.",
    specs: JSON.stringify({ Autonomie: "5 jours", Capteurs: "Fréquence cardiaque, SpO2, temp. cutanée", Résistance: "IP68" }),
    stock: 6, badge: null, is_active: true, created_at: now,
  },

  // ── AUDIO ────────────────────────────────────────────────────────────────────

  {
    id: "jbl-party-box-520",
    name: "JBL PartyBox 520",
    slug: "jbl-party-box-520",
    category_id: "audio", subcategory_id: "enceintes-bluetooth",
    price: 449000, old_price: null, brand: "JBL",
    images: JSON.stringify(img),
    description: "JBL PartyBox 520 — enceinte Bluetooth puissante 240W avec effets lumineux LED et résistance IPX4.",
    specs: JSON.stringify({ Puissance: "240W", Autonomie: "18h", Résistance: "IPX4", Connexion: "Bluetooth 5.3" }),
    stock: 5, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "jbl-party-box-encore",
    name: "JBL PartyBox Encore",
    slug: "jbl-party-box-encore",
    category_id: "audio", subcategory_id: "enceintes-bluetooth",
    price: 349000, old_price: null, brand: "JBL",
    images: JSON.stringify(img),
    description: "JBL PartyBox Encore — enceinte de soirée avec micro sans fil inclus et éclairage dynamique.",
    specs: JSON.stringify({ Puissance: "100W", Autonomie: "6h", Connexion: "Bluetooth 5.1", Micro: "Inclus sans fil" }),
    stock: 7, badge: null, is_active: true, created_at: now,
  },
  {
    id: "dji-mic-3",
    name: "DJI Mic 3",
    slug: "dji-mic-3",
    category_id: "audio", subcategory_id: "micros",
    price: 279000, old_price: null, brand: "DJI",
    images: JSON.stringify(img),
    description: "DJI Mic 3 — micro sans fil compact avec réduction de bruit IA, portée 400m et boîtier de charge.",
    specs: JSON.stringify({ Portée: "400m", Autonomie: "7h + 18h boîtier", Réduction: "Bruit IA", Connexion: "2,4 GHz" }),
    stock: 10, badge: null, is_active: true, created_at: now,
  },
  {
    id: "apple-homepod-2",
    name: "Apple HomePod 2ème Génération",
    slug: "apple-homepod-2",
    category_id: "audio", subcategory_id: "enceintes-intelligentes",
    price: 279000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "Apple HomePod 2ème génération — son spatial immersif, Siri intégré et hub domotique HomeKit.",
    specs: JSON.stringify({ Processeur: "Apple S9", Son: "Spatial Audio", Couleurs: "Minuit, Blanc", Domotique: "HomeKit hub" }),
    stock: 6, badge: null, is_active: true, created_at: now,
  },

  // ── CAMÉRAS & DRONES ─────────────────────────────────────────────────────────

  {
    id: "dji-mini-4-pro-combo",
    name: "DJI Mini 4 Pro — Combo",
    slug: "dji-mini-4-pro-combo",
    category_id: "cameras-drones", subcategory_id: "drones",
    price: 599000, old_price: null, brand: "DJI",
    images: JSON.stringify(img),
    description: "DJI Mini 4 Pro Combo — drone compact 4K HDR avec omnidirectional obstacle sensing et vol 34 min.",
    specs: JSON.stringify({ Poids: "249g", Vidéo: "4K/60fps HDR", Autonomie: "34 min", Portée: "20 km", Résistance: "Level 6 wind" }),
    stock: 6, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "dji-osmo-action-6",
    name: "DJI Osmo Action 6 — Combo",
    slug: "dji-osmo-action-6",
    category_id: "cameras-drones", subcategory_id: "cameras-action",
    price: 349000, old_price: null, brand: "DJI",
    images: JSON.stringify(img),
    description: "DJI Osmo Action 6 Combo — caméra d'action 4K/120fps avec stabilisation RockSteady et résistance -20°C.",
    specs: JSON.stringify({ Vidéo: "4K/120fps", Stabilisation: "RockSteady 4.0", Résistance: "20m étanche", Autonomie: "160 min" }),
    stock: 8, badge: null, is_active: true, created_at: now,
  },
  {
    id: "dji-osmo-pocket-3",
    name: "DJI Osmo Pocket 3",
    slug: "dji-osmo-pocket-3",
    category_id: "cameras-drones", subcategory_id: "cameras-action",
    price: 449000, old_price: null, brand: "DJI",
    images: JSON.stringify(img),
    description: "DJI Osmo Pocket 3 — caméra de poche 4K/120fps avec gimbal 3 axes et suivi de sujet IA.",
    specs: JSON.stringify({ Capteur: "1 pouce CMOS", Vidéo: "4K/120fps", Gimbal: "3 axes", Écran: "2 po tactile" }),
    stock: 7, badge: null, is_active: true, created_at: now,
  },
  {
    id: "dji-osmo-mobile-7",
    name: "DJI Osmo Mobile 7",
    slug: "dji-osmo-mobile-7",
    category_id: "cameras-drones", subcategory_id: "stabilisateurs",
    price: 149000, old_price: null, brand: "DJI",
    images: JSON.stringify(img),
    description: "DJI Osmo Mobile 7 — stabilisateur smartphone léger et pliable avec suivi ActiveTrack 7.0.",
    specs: JSON.stringify({ Poids: "390g", Autonomie: "12h", Suivi: "ActiveTrack 7.0", Bluetooth: "5.1" }),
    stock: 12, badge: null, is_active: true, created_at: now,
  },
  {
    id: "dji-mavic-4-pro",
    name: "DJI Mavic 4 Pro",
    slug: "dji-mavic-4-pro",
    category_id: "cameras-drones", subcategory_id: "drones",
    price: 1299000, old_price: null, brand: "DJI",
    images: JSON.stringify(img),
    description: "DJI Mavic 4 Pro — drone professionnel avec triple caméra Hasselblad et capteur principal 4/3 po.",
    specs: JSON.stringify({ Caméra: "Triple Hasselblad 4/3\"", Vidéo: "6K/60fps", Autonomie: "43 min", Portée: "30 km" }),
    stock: 3, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "dji-rs4-combo",
    name: "DJI RS4 Combo",
    slug: "dji-rs4-combo",
    category_id: "cameras-drones", subcategory_id: "stabilisateurs",
    price: 549000, old_price: null, brand: "DJI",
    images: JSON.stringify(img),
    description: "DJI RS4 Combo — stabilisateur gimbal 3 axes pour reflex et hybrides, charge utile 3 kg.",
    specs: JSON.stringify({ Charge: "3 kg", Axes: "3", Autonomie: "12h", Poids: "1,1 kg" }),
    stock: 5, badge: null, is_active: true, created_at: now,
  },
  {
    id: "canon-eos-5d-mark-iv",
    name: "Canon EOS 5D Mark IV",
    slug: "canon-eos-5d-mark-iv",
    category_id: "cameras-drones", subcategory_id: "appareils-photo",
    price: 1099000, old_price: null, brand: "Canon",
    images: JSON.stringify(img),
    description: "Canon EOS 5D Mark IV avec objectif — reflex full-frame 30,4 Mpx, idéal studio et reportage.",
    specs: JSON.stringify({ Capteur: "Full-frame 30,4 Mpx", Vidéo: "4K/30fps", AF: "61 points", ISO: "100-32000" }),
    stock: 2, badge: null, is_active: true, created_at: now,
  },

  // ── GAMING ───────────────────────────────────────────────────────────────────

  {
    id: "nintendo-switch-oled-2",
    name: "Nintendo Switch OLED 2",
    slug: "nintendo-switch-oled-2",
    category_id: "gaming", subcategory_id: "consoles",
    price: 299000, old_price: null, brand: "Nintendo",
    images: JSON.stringify(img),
    description: "Nintendo Switch OLED 2 — console hybride nouvelle génération avec écran OLED amélioré et performances boostées.",
    specs: JSON.stringify({ Écran: "7 po OLED", Stockage: "128 Go", Autonomie: "8h", Résolution: "1080p TV / 720p portable" }),
    stock: 10, badge: "Nouveau", is_active: true, created_at: now,
  },
  {
    id: "ps5-slim",
    name: "PS5 Slim",
    slug: "ps5-slim",
    category_id: "gaming", subcategory_id: "consoles",
    price: 449000, old_price: null, brand: "Sony",
    images: JSON.stringify(img),
    description: "PS5 Slim Standard — console PlayStation 5 nouvelle version plus compacte avec lecteur de disque.",
    specs: JSON.stringify({ CPU: "AMD Zen 2 8 cœurs", GPU: "10,3 TFLOPS RDNA 2", Stockage: "1 To SSD", Résolution: "4K/120fps" }),
    stock: 8, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "manette-ps5",
    name: "Manette PS5 DualSense",
    slug: "manette-ps5",
    category_id: "gaming", subcategory_id: "manettes-gaming",
    price: 55000, old_price: null, brand: "Sony",
    images: JSON.stringify(img),
    description: "Manette PS5 DualSense neuve scellée — retour haptique, gâchettes adaptatives et micro intégré.",
    specs: JSON.stringify({ Connexion: "USB-C / Bluetooth", Autonomie: "12h", Capteurs: "Gyroscope, accéléromètre" }),
    stock: 20, badge: null, is_active: true, created_at: now,
  },

  // ── IMPRIMANTES ──────────────────────────────────────────────────────────────

  {
    id: "hp-laserjet-mf",
    name: "Imprimante HP LaserJet MF",
    slug: "hp-laserjet-mf",
    category_id: "imprimantes", subcategory_id: "multifonctions",
    price: 349000, old_price: null, brand: "HP",
    images: JSON.stringify(img),
    description: "Imprimante tout-en-un HP LaserJet MF — impression, numérisation et copie laser rapide pour bureau.",
    specs: JSON.stringify({ Type: "Laser N&B multifonction", Vitesse: "28 ppm", Connectivité: "Wi-Fi, USB", Format: "A4" }),
    stock: 5, badge: null, is_active: true, created_at: now,
  },
  {
    id: "hp-color-laserjet-179fnw",
    name: "HP Color LaserJet 179fnw",
    slug: "hp-color-laserjet-179fnw",
    category_id: "imprimantes", subcategory_id: "multifonctions",
    price: 159000, old_price: null, brand: "HP",
    images: JSON.stringify(img),
    description: "HP Color LaserJet 179fnw — multifonction couleur compact avec Wi-Fi et impression mobile.",
    specs: JSON.stringify({ Type: "Laser couleur multifonction", Vitesse: "18 ppm couleur", Connectivité: "Wi-Fi, USB, Ethernet", Format: "A4" }),
    stock: 7, badge: null, is_active: true, created_at: now,
  },
  {
    id: "epson-ecotank-l3250",
    name: "Epson EcoTank L3250",
    slug: "epson-ecotank-l3250",
    category_id: "imprimantes", subcategory_id: "jet-encre",
    price: 215000, old_price: null, brand: "Epson",
    images: JSON.stringify(img),
    description: "Epson EcoTank L3250 couleur A4 Wi-Fi — réservoir rechargeable économique pour impression photo et documents.",
    specs: JSON.stringify({ Type: "Jet d'encre couleur", Réservoirs: "Rechargeables sans cartouche", Connectivité: "Wi-Fi, USB", Format: "A4" }),
    stock: 8, badge: null, is_active: true, created_at: now,
  },
  {
    id: "canon-imagerunner-2930i",
    name: "Canon imageRunner 2930i",
    slug: "canon-imagerunner-2930i",
    category_id: "imprimantes", subcategory_id: "multifonctions",
    price: 699000, old_price: null, brand: "Canon",
    images: JSON.stringify(img),
    description: "Canon imageRunner 2930i — copieur laser N&B professionnel A3 avec recto-verso automatique et réseau.",
    specs: JSON.stringify({ Type: "Laser N&B professionnel", Vitesse: "30 ppm", Format: "A3", Connectivité: "Ethernet, Wi-Fi, USB" }),
    stock: 3, badge: null, is_active: true, created_at: now,
  },
  {
    id: "projecteur-epson",
    name: "Projecteur Epson",
    slug: "projecteur-epson",
    category_id: "imprimantes", subcategory_id: "projecteurs",
    price: 449000, old_price: null, brand: "Epson",
    images: JSON.stringify(img),
    description: "Projecteur Epson — projecteur neuf emballé sous blister, idéal bureaux, salles de réunion et enseignement.",
    specs: JSON.stringify({ Luminosité: "3 600 lumens", Résolution: "Full HD 1080p", Connexion: "HDMI, VGA, USB" }),
    stock: 4, badge: null, is_active: true, created_at: now,
  },

  // ── ACCESSOIRES ──────────────────────────────────────────────────────────────

  {
    id: "microsoft-surface-arc-mouse",
    name: "Microsoft Surface Arc Mouse",
    slug: "microsoft-surface-arc-mouse",
    category_id: "accessoires", subcategory_id: "claviers-souris",
    price: 79000, old_price: null, brand: "Microsoft",
    images: JSON.stringify(img),
    description: "Microsoft Surface Arc Mouse (import USA) — souris Bluetooth ultra-plate qui s'arque pour une prise en main ergonomique.",
    specs: JSON.stringify({ Connexion: "Bluetooth 4.0", Compatibilité: "Windows, Mac", Piles: "AAA x2", Couleurs: "Plusieurs" }),
    stock: 10, badge: null, is_active: true, created_at: now,
  },
  {
    id: "logitech-mx-keys-s",
    name: "Logitech MX Keys S",
    slug: "logitech-mx-keys-s",
    category_id: "accessoires", subcategory_id: "claviers-souris",
    price: 89000, old_price: null, brand: "Logitech",
    images: JSON.stringify(img),
    description: "Logitech MX Keys S — clavier sans fil premium avec rétroéclairage adaptatif et multi-device (3 appareils).",
    specs: JSON.stringify({ Connexion: "Bluetooth / Logi Bolt USB", Rétroéclairage: "Adaptatif", Autonomie: "10 jours éclairé / 5 mois sans" }),
    stock: 12, badge: null, is_active: true, created_at: now,
  },
  {
    id: "magic-keyboard-ipad-m4-pro",
    name: "Magic Keyboard iPad M4 Pro",
    slug: "magic-keyboard-ipad-m4-pro",
    category_id: "accessoires", subcategory_id: "claviers-souris",
    price: 159000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "Magic Keyboard pour iPad Pro M4 — clavier-étui avec trackpad intégré et port USB-C de charge.",
    specs: JSON.stringify({ Compatibilité: "iPad Pro M4 11 / 13 po", Trackpad: "Intégré", Charge: "USB-C pass-through" }),
    stock: 6, badge: null, is_active: true, created_at: now,
  },
  {
    id: "apple-airtag",
    name: "Apple AirTag",
    slug: "apple-airtag",
    category_id: "accessoires", subcategory_id: "chargeurs-cables",
    price: 25000, old_price: null, brand: "Apple",
    images: JSON.stringify(img),
    description: "Apple AirTag — ne perds plus rien. Localisateur Bluetooth intégré au réseau Localiser d'Apple.",
    specs: JSON.stringify({ Connectivité: "Bluetooth 5.0, UWB U1", Résistance: "IP67", Pile: "CR2032" }),
    stock: 30, badge: null, is_active: true, created_at: now,
  },
  {
    id: "sandisk-ssd-externe-1to",
    name: "SanDisk SSD Externe 1 To",
    slug: "sandisk-ssd-externe-1to",
    category_id: "accessoires", subcategory_id: "stockage",
    price: 99000, old_price: null, brand: "SanDisk",
    images: JSON.stringify(img),
    description: "SanDisk SSD externe 1 To — 115 Mo/s en lecture, format ultra-compact et résistant aux chocs.",
    specs: JSON.stringify({ Capacité: "1 To", Lecture: "115 Mo/s", Interface: "USB 3.2 Type-C", Résistance: "Chocs et vibrations" }),
    stock: 15, badge: null, is_active: true, created_at: now,
  },
  {
    id: "ray-ban-meta",
    name: "Ray-Ban Meta Smart Glasses",
    slug: "ray-ban-meta",
    category_id: "accessoires", subcategory_id: "wearables",
    price: 250000, old_price: null, brand: "Ray-Ban",
    images: JSON.stringify(img),
    description: "Ray-Ban Meta — lunettes intelligentes avec IA Meta, caméra 12 Mpx, haut-parleurs ouverts et appels mains libres.",
    specs: JSON.stringify({ Caméra: "12 Mpx", Audio: "Haut-parleurs ouverts", IA: "Meta AI intégrée", Autonomie: "4h" }),
    stock: 8, badge: "Populaire", is_active: true, created_at: now,
  },
  {
    id: "google-nest-hub-2-gen7",
    name: "Google Nest Hub 2ème Génération",
    slug: "google-nest-hub-2-gen7",
    category_id: "accessoires", subcategory_id: "maison-connectee",
    price: 119000, old_price: null, brand: "Google",
    images: JSON.stringify(img),
    description: "Google Nest Hub 2ème génération — écran intelligent 7 po avec Google Assistant, contrôle domotique et suivi du sommeil.",
    specs: JSON.stringify({ Écran: "7 po LCD", Processeur: "Ambient EQ", Connectivité: "Wi-Fi, Bluetooth", Domotique: "Google Home hub" }),
    stock: 7, badge: null, is_active: true, created_at: now,
  },
];

async function main() {
  console.log("Seeding products...");
  await db.delete(products);
  await db.insert(products).values(seed);
  console.log(`✓ ${seed.length} produits insérés`);
}

main().catch((err) => {
  console.error("[seed] Erreur fatale:", err);
  process.exit(1);
});
